version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/backend
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      target: frontend-builder
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    command: npm start